declare const FontSizes: {
    xhalf: string;
    x1: string;
    x2: string;
    x3: string;
    x4: string;
    x5: string;
    x6: string;
    x7: string;
    x8: string;
    x9: string;
    x10: string;
    x11: string;
    x12: string;
    x13: string;
    x14: string;
    x15: string;
    x16: string;
    x17: string;
    x18: string;
    x19: string;
    x20: string;
    x21: string;
    x22: string;
    x23: string;
    x24: string;
    x25: string;
};
export default FontSizes;
